version: "3.4"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./static:/psy_web/static
      - ./media:/psy_web/media
    depends_on:
      - psy_web
    networks:
      - combined-network

  psy_web:
    build: ./psy_web
    container_name: psy_web
    restart: unless-stopped
    volumes:
      - ./static:/psy_web/static
      - ./media:/psy_web/media
      - ./psy_web:/psy_web
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - combined-network

  psy_scheduler:
    build: ./psy_web
    container_name: psy_scheduler
    restart: unless-stopped
    command: >
      sh -c "while true; do
               python manage.py publish_scheduled_pages;
               sleep 60;
             done"
    volumes:
      - ./psy_web:/psy_web
      - ./static:/psy_web/static
      - ./media:/psy_web/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - combined-network

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - combined-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew && docker exec nginx nginx -s reload; sleep 12h & wait $${!}; done;"
    depends_on:
      - nginx
    networks:
      - combined-network

networks:
  combined-network:
    driver: bridge
