version: "3.4"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./static:/psy_web/static
      - ./media:/psy_web/media
    depends_on:
      - psy_web
    networks:
      - combined-network

  psy_web:
    build: ./psy_web
    container_name: psy_web
    volumes:
      - ./static:/psy_web/static
      - ./media:/psy_web/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - combined-network

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - combined-network

    certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew && docker exec nginx nginx -s reload; sleep 12h & wait $${!}; done;"
    depends_on:
      - nginx
    networks:
      - combined-network

networks:
  combined-network:
    driver: bridge